packages:
  - apps/*
  - packages/*
  - config/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma
  - sharp
